-- https://github.com/ellisonleao/gruvbox.nvim/blob/main/lua/gruvbox.lua
local palette = require('gruvbox').palette

require('gruvbox').setup({
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = false,
  italic = {
    strings = false,
    emphasis = false,
    comments = true,
    operators = false,
    folds = false,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  inverse = true,
  contrast = '',
  dim_inactive = false,
  transparent_mode = false,
  palette_overrides = {},
  overrides = {
    NonText = { fg = 'bg' },
    Underlined = { italic = false, underline = false },
    Visual = { bg = palette.dark2, fg = palette.bright_yellow },
    IncSearch = { bg = palette.dark0, fg = palette.bright_orange },
    Comment = { italic = true },
    CursorLine = { ctermbg = 'NONE', bg = 'NONE' },
    LineNr = { bg = 'NONE' },
    SignColumn = { bg = 'NONE' },
    VertSplit = { link = 'Whitespace' },
    NormalFloat = { bg = palette.dark0 },
    FloatBorder = { fg = palette.dark2, bg = palette.dark0 },

    MasonHighlight = { link = 'GruvboxOrange' },
    MasonHighlightBlockBold = { link = 'IncSearch' },
    MasonMutedBlock = { link = 'CursorLine' },

    NvimTreeIndentMarker = { link = 'VertSplit' },
    NvimTreeWinSeparator = { link = 'VertSplit' },
    NvimTreeWindowPicker = { link = 'lualine_a_insert' },

    MiniHipatternsFixme = { fg = nil, bg = nil, bold = false },
    MiniHipatternsHack  = { fg = nil, bg = nil, bold = false },
    MiniHipatternsNote  = { fg = nil, bg = nil, bold = false },
    MiniHipatternsTodo  = { fg = nil, bg = nil, bold = false },

    DiagnosticUnderlineError = { undercurl = true },
    DiagnosticUnderlineHint = { undercurl = true },
    DiagnosticUnderlineInfo = { undercurl = true },
    DiagnosticUnderlineWarn = { undercurl = true },

    DiagnosticSignError = { fg = palette.bright_red, bg = 'NONE' },
    DiagnosticSignHint = { fg = palette.bright_purple, bg = 'NONE' },
    DiagnosticSignInfo = { fg = palette.bright_blue, bg = 'NONE' },
    DiagnosticSignWarn = { fg = palette.bright_yellow, bg = 'NONE' },

    TelescopeBorder = { link = 'FloatBorder' },
    TelescopePromptBorder = { link = 'FloatBorder' },
    TelescopePreviewBorder = { link = 'FloatBorder' },
    TelescopeResultsBorder = { link = 'FloatBorder' },
    TelescopeSelection = { bg = palette.dark1 },
    TelescopeMultiIcon = { fg = palette.neutral_green },

    DevIconConfigru = { link = 'GruvboxRed' },
    DevIconGemfile = { link = 'GruvboxRed' },
    DevIconGemspec = { link = 'GruvboxRed' },
    DevIconRake = { link = 'GruvboxRed' },
    DevIconRakefile = { link = 'GruvboxRed' },
    DevIconRb = { link = 'GruvboxRed' },

    ['@comment.error.comment']   = { fg = nil, bg = nil, bold = nil },
    ['@comment.warning.comment'] = { fg = nil, bg = nil, bold = nil },
    ['@comment.note.comment'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.enum'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.type'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.class'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.event'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.macro'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.method'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.number'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.regexp'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.string'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.struct'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.comment'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.keyword'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.function'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.modifier'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.operator'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.property'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.variable'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.mod.deprecated'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.decorator'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.interface'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.namespace'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.parameter'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.enumMember'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.modifier.java'] = { fg = nil, bg = nil, bold = nil },
    ['@lsp.type.typeParameter'] = { fg = nil, bg = nil, bold = nil },
  },
})
